/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DailyGoalInput = IDL.Record({
  'title' : IDL.Text,
  'date' : IDL.Text,
  'user' : IDL.Principal,
});
export const DailyGoal = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'completed' : IDL.Bool,
});
export const Habit = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const HabitCompletionInput = IDL.Record({
  'date' : IDL.Text,
  'user' : IDL.Principal,
  'habitId' : IDL.Nat,
});
export const HabitCompletion = IDL.Record({
  'date' : IDL.Text,
  'habitId' : IDL.Nat,
});
export const NoteInput = IDL.Record({
  'title' : IDL.Text,
  'body' : IDL.Text,
  'user' : IDL.Principal,
});
export const Note = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'created' : IDL.Int,
  'body' : IDL.Text,
  'updated' : IDL.Int,
});
export const TodoCategory = IDL.Variant({
  'work' : IDL.Null,
  'personal' : IDL.Null,
});
export const TodoInput = IDL.Record({
  'title' : IDL.Text,
  'user' : IDL.Principal,
  'dueDate' : IDL.Opt(IDL.Int),
  'category' : TodoCategory,
});
export const TodoItem = IDL.Record({
  'title' : IDL.Text,
  'created' : IDL.Int,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Opt(IDL.Int),
  'todoId' : IDL.Nat,
  'category' : TodoCategory,
});

export const idlService = IDL.Service({
  'createDailyGoal' : IDL.Func([DailyGoalInput], [DailyGoal], []),
  'createHabit' : IDL.Func([IDL.Text], [Habit], []),
  'createHabitCompletion' : IDL.Func(
      [HabitCompletionInput],
      [HabitCompletion],
      [],
    ),
  'createNote' : IDL.Func([NoteInput], [Note], []),
  'createTodo' : IDL.Func([TodoInput], [TodoItem], []),
  'deleteHabit' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteNote' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteTodo' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllGoals' : IDL.Func([], [IDL.Vec(DailyGoal)], ['query']),
  'getAllTodos' : IDL.Func([], [IDL.Vec(TodoItem)], []),
  'isRegistered' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'markTodoComplete' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DailyGoalInput = IDL.Record({
    'title' : IDL.Text,
    'date' : IDL.Text,
    'user' : IDL.Principal,
  });
  const DailyGoal = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'completed' : IDL.Bool,
  });
  const Habit = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const HabitCompletionInput = IDL.Record({
    'date' : IDL.Text,
    'user' : IDL.Principal,
    'habitId' : IDL.Nat,
  });
  const HabitCompletion = IDL.Record({
    'date' : IDL.Text,
    'habitId' : IDL.Nat,
  });
  const NoteInput = IDL.Record({
    'title' : IDL.Text,
    'body' : IDL.Text,
    'user' : IDL.Principal,
  });
  const Note = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'created' : IDL.Int,
    'body' : IDL.Text,
    'updated' : IDL.Int,
  });
  const TodoCategory = IDL.Variant({
    'work' : IDL.Null,
    'personal' : IDL.Null,
  });
  const TodoInput = IDL.Record({
    'title' : IDL.Text,
    'user' : IDL.Principal,
    'dueDate' : IDL.Opt(IDL.Int),
    'category' : TodoCategory,
  });
  const TodoItem = IDL.Record({
    'title' : IDL.Text,
    'created' : IDL.Int,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Opt(IDL.Int),
    'todoId' : IDL.Nat,
    'category' : TodoCategory,
  });
  
  return IDL.Service({
    'createDailyGoal' : IDL.Func([DailyGoalInput], [DailyGoal], []),
    'createHabit' : IDL.Func([IDL.Text], [Habit], []),
    'createHabitCompletion' : IDL.Func(
        [HabitCompletionInput],
        [HabitCompletion],
        [],
      ),
    'createNote' : IDL.Func([NoteInput], [Note], []),
    'createTodo' : IDL.Func([TodoInput], [TodoItem], []),
    'deleteHabit' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteNote' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteTodo' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllGoals' : IDL.Func([], [IDL.Vec(DailyGoal)], ['query']),
    'getAllTodos' : IDL.Func([], [IDL.Vec(TodoItem)], []),
    'isRegistered' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'markTodoComplete' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };