/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyGoal {
  'id' : bigint,
  'title' : string,
  'date' : string,
  'completed' : boolean,
}
export interface DailyGoalInput {
  'title' : string,
  'date' : string,
  'user' : Principal,
}
export interface Habit { 'id' : bigint, 'name' : string }
export interface HabitCompletion { 'date' : string, 'habitId' : bigint }
export interface HabitCompletionInput {
  'date' : string,
  'user' : Principal,
  'habitId' : bigint,
}
export interface Note {
  'id' : bigint,
  'title' : string,
  'created' : bigint,
  'body' : string,
  'updated' : bigint,
}
export interface NoteInput {
  'title' : string,
  'body' : string,
  'user' : Principal,
}
export type TodoCategory = { 'work' : null } |
  { 'personal' : null };
export interface TodoInput {
  'title' : string,
  'user' : Principal,
  'dueDate' : [] | [bigint],
  'category' : TodoCategory,
}
export interface TodoItem {
  'title' : string,
  'created' : bigint,
  'completed' : boolean,
  'dueDate' : [] | [bigint],
  'todoId' : bigint,
  'category' : TodoCategory,
}
export interface _SERVICE {
  'createDailyGoal' : ActorMethod<[DailyGoalInput], DailyGoal>,
  'createHabit' : ActorMethod<[string], Habit>,
  'createHabitCompletion' : ActorMethod<
    [HabitCompletionInput],
    HabitCompletion
  >,
  'createNote' : ActorMethod<[NoteInput], Note>,
  'createTodo' : ActorMethod<[TodoInput], TodoItem>,
  'deleteHabit' : ActorMethod<[bigint], boolean>,
  'deleteNote' : ActorMethod<[bigint], boolean>,
  'deleteTodo' : ActorMethod<[bigint], boolean>,
  'getAllGoals' : ActorMethod<[], Array<DailyGoal>>,
  'getAllTodos' : ActorMethod<[], Array<TodoItem>>,
  'isRegistered' : ActorMethod<[Principal], boolean>,
  'markTodoComplete' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];