/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface NoteInput {
    title: string;
    body: string;
    user: Principal;
}
export interface DailyGoal {
    id: bigint;
    title: string;
    date: string;
    completed: boolean;
}
export interface HabitCompletion {
    date: string;
    habitId: bigint;
}
export interface TodoItem {
    title: string;
    created: bigint;
    completed: boolean;
    dueDate?: bigint;
    todoId: bigint;
    category: TodoCategory;
}
export interface HabitCompletionInput {
    date: string;
    user: Principal;
    habitId: bigint;
}
export interface Habit {
    id: bigint;
    name: string;
}
export interface DailyGoalInput {
    title: string;
    date: string;
    user: Principal;
}
export interface TodoInput {
    title: string;
    user: Principal;
    dueDate?: bigint;
    category: TodoCategory;
}
export interface Note {
    id: bigint;
    title: string;
    created: bigint;
    body: string;
    updated: bigint;
}
export enum TodoCategory {
    work = "work",
    personal = "personal"
}
export interface backendInterface {
    createDailyGoal(input: DailyGoalInput): Promise<DailyGoal>;
    createHabit(name: string): Promise<Habit>;
    createHabitCompletion(input: HabitCompletionInput): Promise<HabitCompletion>;
    createNote(input: NoteInput): Promise<Note>;
    createTodo(input: TodoInput): Promise<TodoItem>;
    deleteHabit(id: bigint): Promise<boolean>;
    deleteNote(id: bigint): Promise<boolean>;
    deleteTodo(id: bigint): Promise<boolean>;
    getAllGoals(): Promise<Array<DailyGoal>>;
    getAllTodos(): Promise<Array<TodoItem>>;
    isRegistered(user: Principal): Promise<boolean>;
    markTodoComplete(id: bigint): Promise<void>;
}
import type { TodoCategory as _TodoCategory, TodoInput as _TodoInput, TodoItem as _TodoItem } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createDailyGoal(arg0: DailyGoalInput): Promise<DailyGoal> {
        if (this.processError) {
            try {
                const result = await this.actor.createDailyGoal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDailyGoal(arg0);
            return result;
        }
    }
    async createHabit(arg0: string): Promise<Habit> {
        if (this.processError) {
            try {
                const result = await this.actor.createHabit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHabit(arg0);
            return result;
        }
    }
    async createHabitCompletion(arg0: HabitCompletionInput): Promise<HabitCompletion> {
        if (this.processError) {
            try {
                const result = await this.actor.createHabitCompletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHabitCompletion(arg0);
            return result;
        }
    }
    async createNote(arg0: NoteInput): Promise<Note> {
        if (this.processError) {
            try {
                const result = await this.actor.createNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNote(arg0);
            return result;
        }
    }
    async createTodo(arg0: TodoInput): Promise<TodoItem> {
        if (this.processError) {
            try {
                const result = await this.actor.createTodo(to_candid_TodoInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_TodoItem_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTodo(to_candid_TodoInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_TodoItem_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteHabit(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHabit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHabit(arg0);
            return result;
        }
    }
    async deleteNote(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNote(arg0);
            return result;
        }
    }
    async deleteTodo(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTodo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTodo(arg0);
            return result;
        }
    }
    async getAllGoals(): Promise<Array<DailyGoal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGoals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGoals();
            return result;
        }
    }
    async getAllTodos(): Promise<Array<TodoItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTodos();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTodos();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async isRegistered(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isRegistered(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isRegistered(arg0);
            return result;
        }
    }
    async markTodoComplete(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markTodoComplete(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markTodoComplete(arg0);
            return result;
        }
    }
}
function from_candid_TodoCategory_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TodoCategory): TodoCategory {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_TodoItem_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TodoItem): TodoItem {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    created: bigint;
    completed: boolean;
    dueDate: [] | [bigint];
    todoId: bigint;
    category: _TodoCategory;
}): {
    title: string;
    created: bigint;
    completed: boolean;
    dueDate?: bigint;
    todoId: bigint;
    category: TodoCategory;
} {
    return {
        title: value.title,
        created: value.created,
        completed: value.completed,
        dueDate: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.dueDate)),
        todoId: value.todoId,
        category: from_candid_TodoCategory_n8(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    work: null;
} | {
    personal: null;
}): TodoCategory {
    return "work" in value ? TodoCategory.work : "personal" in value ? TodoCategory.personal : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TodoItem>): Array<TodoItem> {
    return value.map((x)=>from_candid_TodoItem_n5(_uploadFile, _downloadFile, x));
}
function to_candid_TodoCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TodoCategory): _TodoCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_TodoInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TodoInput): _TodoInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    user: Principal;
    dueDate?: bigint;
    category: TodoCategory;
}): {
    title: string;
    user: Principal;
    dueDate: [] | [bigint];
    category: _TodoCategory;
} {
    return {
        title: value.title,
        user: value.user,
        dueDate: value.dueDate ? candid_some(value.dueDate) : candid_none(),
        category: to_candid_TodoCategory_n3(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TodoCategory): {
    work: null;
} | {
    personal: null;
} {
    return value == TodoCategory.work ? {
        work: null
    } : value == TodoCategory.personal ? {
        personal: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
